name: Greetings

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  greeting:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Bangkok'
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
