name: Fetch Random Picture
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  random_picture:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Bangkok"
    steps:
      - name:  login
        run: |
          git config --global user.email "pxr@gmail.com"
          git config --global user.name "pxr"
          git clone https://github.com/mkdev55/testing.git
          cd testing
          git pull
          rm image.jpg
          git remote remove origin
          git remote add origin https://mkdev55:${{secrets.TOKEN}}@github.com/mkdev55/testing.git
          curl -o image.jpg https://picsum.photos/300/300
          git add .
          git commit -m 'test'
          git push origin main
          
          
