name: Fetch Random Picture
on:
  push:
    branches:
      - main

jobs:
  random_picture:
    runs-on: ubuntu-latest

    steps:
      - name:  login
        run: |
          whoami
          cat /etc/os-release
          echo ${{ secrets.TOKEN }}
