name: Fetch Random Picture
on:
  push:
    branches:
      - main

jobs:
  random_picture:
    runs-on: ubuntu-latest

    steps:
      - name:  login
        run: |
          git config --global user.email "pxr@gmail.com"
          git config --global user.name "pxr"
          git clone https://github.com/mkdev55/testing.git
          cd testing
          git remote remove origin
          git remote add origin https://mkdev55:${{secrets.TOKEN}}@github.com/mkdev55/testing.git
          curl -o index.html https://www.youtube.com
          git add .
          git commit -m 'test'
          git push origin main
          
          
